### ISSUE TITLE
Deploy Script fails when chossing to create a new Resource Gorup

### ISSUE THREAD

**Issue by jplummer01** [microsoft/Build-your-own-copilot-Solution-Accelerator#19]
Script fails when trying to deploy and create a new RG. Requires that you pre-create a CognitiveServices Resource in the RG and accept the RAI Principles...then fails as per the other issue in the repo already documented

**Comment by megangavin** [comment]
Thank you for your feedback @jplummer01. Our team will review and respond to your logged issue. Your patience is appreciated.

**Comment by Roopan-Microsoft** [comment]
Hi @jplummer01, could you please confirm whether you're experiencing this issue with the Client Advisor or the Research Assistant accelerator, so that we can investigate accordingly?

**Comment by Roopan-Microsoft** [comment]
Hi @jplummer01 - Can you please post your error screenshot while we are investigating the issue and please let us know the repro steps as well. Thanks.

**Comment by Roopan-Microsoft** [comment]
Hey @jplummer01 - I believe you were getting this issue "
"{"code":"InvalidTemplateDeployment","details":[{"code":"ResourceKindRequireAcceptTerms","message":"This subscription cannot create CognitiveServices until you agree to Responsible AI terms for this resource. You can agree to Responsible AI terms by creating a resource through the Azure Portal then trying again. For more detail go to [https://aka.ms/csrainotice"}],"message":"The](https://aka.ms/csrainotice%22%7D],%22message%22:%22The) template deployment 'Microsoft.Template-20240820112902' is not valid according to the validation procedure. The tracking id is '2c1a9ed7-d4a6-4f27-a4f6-a94c0de96688'. See inner errors for details."}""

If Yes, please create the Azure AI Services manually and accept the terms once, so this error will not appear again.

Try manually creating a resource in Azure Portal > Create Resource > Search "Language Service" -> create -> language service -> continue to create your resource -> then there's a check box on the lower part for the responsible AI Notice

Ref Link - https://learn.microsoft.com/en-us/answers/questions/464330/how-can-i-check-the-responsible-ai-notice-while-cr?page=3#answers

**Comment by megangavin** [comment]
@jplummer01, with instruction provided above, closing this ticket. Happy to help with any further issues should they arise.
