### ISSUE TITLE
Error during deployment: 'gpt-4 0125-Preview' is not supported

### ISSUE THREAD

**Issue by mdt-mymeta** [microsoft/Build-your-own-copilot-Solution-Accelerator#35]
Hi,
I launched the Deployment procedure for [ClientAdvisor](https://github.com/microsoft/Build-your-own-copilot-Solution-Accelerator/tree/main/ClientAdvisor).
During the deployment process I got
"{"code":"InvalidTemplateDeployment","details":[{"code":"InvalidResourceProperties","message":"The specified SKU 'Standard' for model 'gpt-4 0125-Preview' is not supported in this region 'francecentral'."},

I saw the suggested model now is "gpt-4 Version: turbo-2024-04-09", is it possible to update this configuration?

Regards

**Comment by megangavin** [comment]
Thank you for your feedback @mdt-mymeta. Our team will review and respond to your logged issue. Your patience is appreciated.

**Comment by Roopan-Microsoft** [comment]
Hi @mdt-mymeta - We see the above-mentioned versions are not supported in France Central.
Link - https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#standard-deployment-model-availability
<img width="902" alt="image" src="https://github.com/user-attachments/assets/1c03e6ce-ea7e-48c4-8a36-40e35e0775ee">

We are investigating. if you can update the GPT Version in the template during the deployment. We will update you shortly.

Meanwhile you can try choosing the other supported regions as well. Thanks,

**Comment by Prasanjeet-Microsoft** [comment]
Hi @mdt-mymeta, We are pleased to inform you that we have updated the template to the gpt-4-0613 model, which is supported in France Central. The deployment was completed successfully without any issues. Please see the screenshot below for your reference:

![image](https://github.com/user-attachments/assets/683b27d2-d728-41f1-9be2-83035306a3da)

![image](https://github.com/user-attachments/assets/292f7258-dae1-4587-bdaa-a223df93e46f)

FYI @Roopan-Microsoft

**Comment by mdt-mymeta** [comment]
Hi,
thanks for the support, I got again
{
  "code": "InvalidTemplateDeployment",
  "details": [
    {
      "code": "InvalidResourceProperties",
      "message": "The specified SKU 'Standard' for model 'gpt-4 0125-Preview' is not supported in this region 'francecentral'."
    }
  ],
  "message": "The template deployment 'Microsoft.Template-20240823093555' is not valid according to the validation procedure. The tracking id is '197789be-7915-414c-9720-7f9f7dd3274a'. See inner errors for details."
}

but I used the
![image](https://github.com/user-attachments/assets/54259724-906c-4845-88a7-2463db6a469a)

is there another procedure I need to follow?

Regards

**Comment by Roopan-Microsoft** [comment]
Hi @mdt-mymeta , Please follow the below steps to change the Gpt version in the template,


- Click 'Deploy to Azure' from the GitHub Repo
- Click 'Edit Template' 
- <img width="386" alt="image" src="https://github.com/user-attachments/assets/262c7adb-9551-44d0-aaa4-7665b4a3b60e">
- Search & replace "0125-Preview" -> "0613" version which is supported in France Central
- <img width="908" alt="image" src="https://github.com/user-attachments/assets/2cb3e189-8224-4499-9bdb-bf96d6c9cd5b">
-  Click "Save" and "Review + Create" post provided all details.

Please let us know in case any issues.

**Comment by Prasanjeet-Microsoft** [comment]
Hello @mdt-mymeta , could you please confirm whether you are able to deploy it? If so, can we go ahead and close this issue?

**Comment by Prasanjeet-Microsoft** [comment]
Hello @mdt-mymeta , With the instructions provided above, I am closing this ticket. If you have any further issues, feel free to reach out. 

FYI @Roopan-Microsoft

**Comment by mdt-mymeta** [comment]
It works, thanks
