### ISSUE TITLE
deploy_index_script and deploy_aihub_script failed to complete successfully

### ISSUE THREAD

**Issue by ahmedbham** [microsoft/Build-your-own-copilot-Solution-Accelerator#8]
Both these scripts failed to complete.  
![Deployment Failure](https://github.com/microsoft/Build-your-own-AI-Assistant-Solution-Accelerator/assets/16580429/ddf21bdf-651e-4bad-91b3-8203545bbb16)

In addition, no secrets were created in KV.

**Comment by megangavin** [comment]
@abossard - Thank you for the note. Our team will revisit and keep you posted.

**Comment by jplummer01** [comment]
The problem still existis on 4th July

**Comment by megangavin** [comment]
Thank you @jplummer01. Our team is troubleshooting and will post an update here once we find the issue successfully resolved.

**Comment by megangavin** [comment]
@ahmedbham, @abossard, and @jplummer01 - Updates have been made and deployment completed successfully.
